### ISSUE TITLE
Abstract: Manuall configuration

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis#1788]
Recommends implementing the way that Online/Locall installers behave in all supported software e.i: if user wants to install GAME A -> perform installer and allow user to check wine version and dependencies, etc.. that he/she want's to use with recommended option from phoenicis.

Working configuration can then be exported for pull request.

Also this way we can add all games from origin, steam, etc.. and allow user to make his own configuration for software that is not yet supported.

### Expected behavior
Making reporting easier, making scripts easier, testing scripts easier, more functionality and usefullness, encourage new contributors

### Actual behavior
Scripts has to be made by hand and testing is not effective enough + phoenicis lacks user-friendly configuration.

**Comment by Kreyren** [comment]
@plata well practically we have that as a separate program, but i believe that this implementation is more effective for reasons above.

**Comment by plata** [comment]
In any case we should split this. One part is manual Steam script etc., the other one is create a script based on the current container configuration.
The first one is definitely possible. About the second I'm not really sure.

**Comment by Kreyren** [comment]
@plata Why wouldn't it be possible? afaik it would read configuration from specified repository?

**Comment by plata** [comment]
We do not store the installation steps anywhere, the user can change the container from outside Phoenicis and our scripts are not declarative. Therefore the generated script might produce quite different results from what you did manually.

**Comment by madoar** [comment]
@Kreyren why should a user want to change the script configuration prior to the installation?
A normal user wants to execute a script without performing any configuration. It's also quite possible that he has no experience at all with wine etc.

**Comment by Kreyren** [comment]
@madoar For cases where script provided by phoenicis is not working as expected mainly. 

Note that i'm suggesting to add the option not to replace the phoenicis scripts.

**Comment by madoar** [comment]
If a script is not working as expected it likely contains a bug and should be fixed in the main repository.
I don't see how a manual configuration prior to the installation helps here?

**Comment by Kreyren** [comment]
> But why can't the user simply fork the repository, perform his changes on the fork, test it and then open a PR?

He/she can but that requires making a local/remote repository. 

My suggestion would implement a feature that is already present in phoenicis and utilized it better without the need to make local/remote repository as a frontend for engine configuration + that way we would be able to make a passive support for scripts that are not supported instead of making quick scripts that rarely works based on my experience.. 

> Phoenicis wants to provide two repositories later ...

practically what i suggested in https://github.com/PhoenicisOrg/scripts/issues/820 ? Practically having the same 'wizard' in web and software interface would be also very effective.. 

> As you cannot uninstall verbs, you must reinstall anyways.

That can also be implemented in that wizard..


---

Practically we have Online/Local Installers as standalone programs in phoenicis i'm suggesting to remove those and introduce them as a function in settings so that we can provide all games from steam, origin, uplay, etc.. pasively and make their testing/development way more effective this way with the ability to use scripts provided by phoenicis on demand.

**Comment by plata** [comment]
With the linked issues solved, it will be possible to e.g. install any Steam game, select the Wine version etc. which shall be used for it and install verbs.

The next step would be to "record" the custom installation. I'm still not yet fully convinced how useful this is.

**Comment by plata** [comment]
Adding a script generator to Phoenicis directly will bloat up the GUI for the average user. Therefore we will not implement this.
